server:
  port: 9527

spring:
  application:
    name: consul-gatewat
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/payment/get/**
            - After=2021-05-02T15:00:03.685+08:00[Asia/Shanghai]
            - Cookie=username,zzyy

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka/


